Entities/Category.cs
using System;
namespace admin_panel.Entities
{
	public class Category
	{
		public int Id { get; set; }
		public string Name { get; set; }


		public List<Product> Products { get; set; }
	}
}

Entities/Customer.cs
using System;
namespace admin_panel.Entities
{
	public class Customer
	{
		public int Id { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string Email { get; set; }

		public List<Order> Orders { get; set; }
	}
}

Entities/Order.cs
using System;
namespace admin_panel.Entities
{
	public class Order
	{
		public int Id { get; set; }
		public DateTime OrderDate { get; set; }
		public int ProductId { get; set; }
		public int CustomerId { get; set; }

		public List<Product> Products { get; set; }
		public List<Customer> Customers { get; set; }
	}
}

Entities/Product.cs
using System;
namespace admin_panel.Entities
{
	public class Product
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public decimal Price { get; set; }
		public string? ProductImageId { get; set; }
		public int CategoryId { get; set; }

		public ProductImage? productImage { get; set; }
		public Category Category { get; set; }
		public List<Order> Orders { get; set; }
	}
}

Entities/ProductImage.cs
using System;
namespace admin_panel.Entities
{
	public class ProductImage
	{
		public int Id { get; set; }
		public string ImageName { get; set; }

		public Product Product { get; set; }
	}
}

Models/CategoriesVM.cs
using System;
using admin_panel.Entities;

namespace admin_panel.Models
{
	public class CategoriesVM
	{
		public List<Category> Categories { get; set; }
	}
}

Models/ErrorViewModel.cs
namespace admin_panel.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/ProductsVM.cs
using System;
using admin_panel.Entities;

namespace admin_panel.Models
{
	public class ProductsVM
	{
		public List<Product>? Products { get; set; }
	}
}

Controllers/CategoriesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using admin_panel.Models;
using admin_panel.Data;
using admin_panel.Entities;
using Microsoft.EntityFrameworkCore;

namespace admin_panel.Controllers;

public class CategoriesController : Controller
{
    private AppDbContext _dbContext;

    public CategoriesController(AppDbContext dbContext)
    {
        _dbContext = dbContext;
    }
    public IActionResult Index()
    {
        var categories = _dbContext.Categories.Include(x => x.Products).ToList();
        var model = new CategoriesVM
        {
            Categories = categories
        };
        return View(model);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace admin_panel.Controllers
{
    public class CustomersController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace admin_panel.Controllers
{
    public class OrdersController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using admin_panel.Data;
using admin_panel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace admin_panel.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AppDbContext _dbContext;

        public ProductsController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var products = _dbContext.Products.Include(x => x.Category).ToList();
            var model = new ProductsVM
            {
                Products = products
            };
            return View(model);
        }
    }
}

Views/Categories/Index.cshtml
@model CategoriesVM;
@{
    ViewData["Title"] = "Home Page";
}

<div class="title">
    <p>Categories</p>
    <button>Add+</button>
</div>

<div class="box-container">
    @foreach (var category in Model.Categories)
    {
        <div class="categories-box">
            <div class="category-name">
                <p>@category.Name</p>
            </div>
        </div>
    }

</div>

Views/Customers/Index.cshtml
@page
@{
}

<div class="title">
    <p>Customers</p>
    <button>Add+</button>
</div>

<div class="box-container">
    <div class="categories-box">
        <div class="category-name">
            <p class="customerName">Customer Name: Zilish</p>
            <p class="customerEmail">Customer Email: zilishiz@code.edu.az</p>
        </div>
    </div>
</div>

Views/Orders/Index.cshtml
@page
@{
}

<div class="title">
    <p>Orders</p>
    <button>Add+</button>
</div>

    

<div class="box-container">
    <div class="categories-box">
        <div class="category-name">
            <div class="img">
                <img src="" alt="shekil">
            </div>
            <p class="productName">Product Name: Corek</p>
            <p class="customerName">Customer Name: Food</p>
            <p class="productPrice">Product Price: 123</p>
            <p class="orderDate">Order Date: 12.12.2012</p>
        </div>
    </div>
</div>

Views/Products/Index.cshtml
@model ProductsVM;
@{
}

<div class="title">
    <p>Products</p>
    <button>Add+</button>
</div>

<div class="box-container">
    @foreach (var product in Model.Products)
    {
        <div class="categories-box">
            <div class="category-name">
                <div class="img">
                    <img src="" alt="shekil">
                </div>
                <p class="productName">Product Name: @product.Name</p>
                <p class="productCategory">Product Category: @product.Category</p>
                <p class="productPrice">Product Price: @product.Price</p>
            </div>
        </div>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - admin_panel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/admin_panel.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/category.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Categories" asp-action="Index">admin_panel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - admin_panel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>